### ISSUE TITLE
[Accordion] Documentation errors

### ISSUE THREAD

**Issue by wfehr** [zurb/foundation-sites#10096]
The doc for the [accordion](http://foundation.zurb.com/sites/docs/accordion.html) has a section "[Deep Linking](http://foundation.zurb.com/sites/docs/accordion.html#deep-linking)". When I download the newest .tar.gz of foundation-sites it doesn't have this feature inside of dist/js/. The source JavaScript files under js/ are having the code needed for it.
I looked at the changelog for v6.3.1 and I couldn't find the changes for deep-linking, but the docs for version 6.3.1 say it is available.

Was it just forgotten to include in dist/ or is it an error in the docs?

**Comment by garrett-eclipse** [comment]
@wfehr I've also recently come across this, was odd that the download from several places didn't have it.

I tried downloading from github, along with;
https://github.com/zurb/foundation-sites/releases/
AND
http://foundation.zurb.com/sites/download.html/

But it's not evident in any of these packages so must have been missed on compile or something.

Anyway I just grabbed the .js file directly from the documentation site to use in the meantime, can be found here;
http://foundation.zurb.com/sites/docs/assets/js/foundation.js?hash=cc77c8f1742c310a128dfc82e4e6fe47

**Comment by wfehr** [comment]
So I upgraded to the new version 6.4.1 of foundation (previous used version was 6.3.1) and now technically the deep-linking of the accordion would work.

But: When I link to an accordion (e.g. mysite.com/#foo) I get the following JavaScript error:

```
foundation.js:5495
TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (jquery.js:9823)
    at Accordion._checkDeepLink (foundation.js:1683)
    at Accordion._init (foundation.js:1700)
    at Accordion._setup (foundation.js:1621)
    at Accordion.Plugin (foundation.js:164)
    at new Accordion (foundation.js:1602)
    at HTMLUListElement.<anonymous> (foundation.js:5493)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at String.<anonymous> (foundation.js:5475)
```

**Comment by dkellner** [comment]
This error even occurs in the docs: http://foundation.zurb.com/sites/docs/accordion.html#deeplink2

```
14:27:48.143 TypeError: url.indexOf is not a function
Stack-Trace:
jQuery.fn.load@http://foundation.zurb.com/sites/docs/assets/js/vendor.js?hash=d18b128a39a0ffe516794280256ae5a4:9823:9
_init/this._checkDeepLink@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.accordion.js?hash=a8ce3330922bb547822b630db7273f22:235:15
_init@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.accordion.js?hash=a8ce3330922bb547822b630db7273f22:252:9
_setup@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.accordion.js?hash=a8ce3330922bb547822b630db7273f22:173:7
Plugin@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js?hash=98837e50495b364158de00afb0052996:553:5
Accordion@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.accordion.js?hash=a8ce3330922bb547822b630db7273f22:154:46
reflow/</<@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js?hash=98837e50495b364158de00afb0052996:356:32
each@http://foundation.zurb.com/sites/docs/assets/js/vendor.js?hash=d18b128a39a0ffe516794280256ae5a4:362:10
each@http://foundation.zurb.com/sites/docs/assets/js/vendor.js?hash=d18b128a39a0ffe516794280256ae5a4:157:10
reflow/<@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js?hash=98837e50495b364158de00afb0052996:338:7
each@http://foundation.zurb.com/sites/docs/assets/js/vendor.js?hash=d18b128a39a0ffe516794280256ae5a4:362:10
reflow@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js?hash=98837e50495b364158de00afb0052996:330:5
foundation@http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js?hash=98837e50495b364158de00afb0052996:385:9
@http://foundation.zurb.com/sites/docs/assets/js/docs.js?hash=70133a3b5501151a601ee22c0d445fe7:3895:1
 1 foundation.core.js:358:11
	reflow/</< http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js:358:11
	each http://foundation.zurb.com/sites/docs/assets/js/vendor.js:362:10
	each http://foundation.zurb.com/sites/docs/assets/js/vendor.js:157:10
	reflow/< http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js:338:7
	each http://foundation.zurb.com/sites/docs/assets/js/vendor.js:362:10
	reflow http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js:330:5
	foundation http://foundation.zurb.com/sites/docs/assets/js/plugins/foundation.core.js:385:9
	<anonym> http://foundation.zurb.com/sites/docs/assets/js/docs.js:3895:1
```

**Comment by wfehr** [comment]
I just installed foundation V. 6.4.3 and checked deeplinking, but the problem is there. Also in the documentation it still exists.

**Comment by DanielRuf** [comment]
The problem is that jQuery.load expects a URL, this is meant for dynamically loading content from URLs.

http://api.jquery.com/load/

See the warning in the yellow box.

> Note: Prior to jQuery 3.0, the event handling suite also had a method named .load(). Older versions of jQuery determined which method to fire based on the set of arguments passed to it.

Solution: use `.on( "load", handler )`

**Comment by DanielRuf** [comment]
See https://github.com/zurb/foundation-sites/pull/10729

**Comment by ajoy39** [comment]
This issue is still occurring, including in the docs. if you go to http://foundation.zurb.com/sites/docs/accordion.html#deeplink2 the accordion no longer works. This only happens if you try to go the page with a a deeplink, if you load the page without the deeplink the accordion will continue to work. 

In addition, and this may be unrelated, but the "smudge" doesn't work even when you go to the page without the deeplink. It doesn't scroll to the top of the opened accordion section when you open a new one.

**Comment by DanielRuf** [comment]
It was fixed int eh develop branch and will land in 6.5.

**Comment by DanielRuf** [comment]
> @ncoden ncoden merged commit 7839710 into zurb:develop  on 24 Dec 2017

**Comment by wfehr** [comment]
Just installed and tested the linking with the develop branch and it still doesn't work properly. Getting the same error as in the docs:
`foundation.core.js?hash=609740d9dc497dd1e4c7cfb8d31742fc:14`
`TypeError: url.indexOf is not a function
    at jQuery.fn.init.jQuery.fn.load (vendor.js?hash=92a493d…:651)
    at Accordion._checkDeepLink (foundation.accordion.js?hash=76f630e…:9)
    at Accordion._init (foundation.accordion.js?hash=76f630e…:10)
    at Accordion._setup (foundation.accordion.js?hash=76f630e…:8)
    at Accordion.Plugin (foundation.core.js?hash=609740d…:24)
    at new Accordion (foundation.accordion.js?hash=76f630e…:7)
    at HTMLUListElement.<anonymous> (foundation.core.js?hash=609740d…:14)
    at Function.each (vendor.js?hash=92a493d…:27)
    at jQuery.fn.init.each (vendor.js?hash=92a493d…:17)
    at String.<anonymous> (foundation.core.js?hash=609740d…:12)`

**Comment by DanielRuf** [comment]
@wfehr what exact steps did you take? You might have to run `npm start` or `npm run deploy` to build the dist files.

**Comment by DanielRuf** [comment]
https://github.com/zurb/foundation-sites/tree/develop/dist is not the latest development status.
Deployments are just done for releases.

cc @ncoden how is our current schedule which we can communicate?

**Comment by CreateSean** [comment]
I've hit this issue just now. Is there a fix that I can apply somewhere in Foundation 6.4.3 in order to get this working correctly?

**Comment by DanielRuf** [comment]
In general you can try building from dev branch (manually compile Foundation).

**Comment by DanielRuf** [comment]
> @DanielRuf I guess we will try to resolve all the issues that were reported for v6.5.0-rc.1 and publish an RC2 after that. So they may be a stable release around July 7th. What do you think ?

Sounds good.
