### ISSUE TITLE
Precompile the library to CommonJS.

### ISSUE THREAD

**Issue by ShadyXV** [zurb/foundation-sites#10774]
Trying to run tests with Jest doesn't work after importing foundation-sites on the component.
[#2937](https://github.com/facebookincubator/create-react-app/issues/2937)

**Comment by Pharserror** [comment]
👍  on this.

**Comment by ncoden** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/10864

**Comment by bobwalker99** [comment]
The change made in #10864 doesn't fix the referenced create-react-app issue (facebook/create-react-app#2937) - The problem is with the jQuery import (`import $ from jQuery';`).

To recreate:

1. Create a react app with the standard commands:
```
npx create-react-app my-app
cd my-app
npm start
```
2. Add a reference to the develop branch of foundation-sites in package.json:
```
yarn add zurb/foundation-sites#develop
```
3. Edit `src\App.js` and add the following:
```
import { Foundation } from "foundation-sites/js/foundation.core";
```
4. run `yarn test`. output is as follows:
```
 FAIL  src\App.test.js
  ● Test suite failed to run

    C:\Users\bob.walker\dev\my-app\node_modules\foundation-sites\js\foundation.core.js:3
    import $ from 'jquery';
    ^^^^^^

    SyntaxError: Unexpected token import

      at new Script (vm.js:51:7)
      at Object.<anonymous> (src/App.js:4:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.685s
Ran all test suites related to changed files.
```

Changing all the imports in the foundation source (under my app's `node_modules`) to `import {$} from jQuery;` fixes it for me, but I tried forking and making this change in the foundation-sites project, but I get test failures that I don't get before the change. Happy to investigate further if someone can provide guidance?

**Comment by ncoden** [comment]
@bobwalker99 `foundation-sites/js/foundation.core` is the source file and will always be in ES6+. Please use the following instead to import Foundation from the precompiled dist file:

```js
import { Foundation } from 'foundation-sites';
```
Or to get the core only:
```js
import { Foundation } from 'foundation-sites/dist/js/plugins/foundation.core';
```

I don't see how using `import {$} from jQuery;` would fix anything.
