### ISSUE TITLE
[Accordion Menu] is-active class on inactive ul not getting removed

### ISSUE THREAD

**Issue by bitbruder** [zurb/foundation-sites#11383]
## What should happen?
When closing a accordion-menu-item via a subtoggler in a accordion-menu, the class `is-active` should be removed from the ul within the list-item.

## What happens instead?
The class `is-active` stays on the element, even if you close the item via a subtoggler.

## Possible Solution
The class is added in the "down" event: 
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.accordionMenu.js#L243

The class should be removed in the "up" event, but its missing: 
https://github.com/zurb/foundation-sites/blob/develop/js/foundation.accordionMenu.js#L266

## Test Case and/or Steps to Reproduce

Test Case:
You can check out the docs at:
https://foundation.zurb.com/sites/docs/accordion-menu.html#submenu-toggle

Just inspect the `<ul>` and check out the `is-active` class.

## Context
I want to style the active state of menu elements, this is almost impossible without a proper active class on the parent of the toggled element.

## Your Environment

- Foundation version(s) used: 6.4.1
- Browser(s) name and version(s): Chrome 67
- Operating System and version (desktop or mobile): macOS

## Checklist (all required):

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title is descriptive.
- [x] The template is correctly filled.

**Comment by DanielRuf** [comment]
> active class on the parent of the toggled element

So we also need a class on the parent element which houses the submenu.

**Comment by ncoden** [comment]
Related to https://github.com/zurb/foundation-sites/issues/11467
Fixed by https://github.com/zurb/foundation-sites/pull/11469

**Comment by Bakuryu** [comment]
This is still happening for me even when using the latest js file.

**Comment by DanielRuf** [comment]
> This is still happening for me even when using the latest js file.

Please provide a working codepen so we can reproduce it and create a new issue.

**Comment by Bakuryu** [comment]
https://codepen.io/Bakuryu/pen/RqRRNK?editors=1000

**Comment by DanielRuf** [comment]
> and create a new issue.

Please post the codepen link in a new issue with all relevant details (use one of the issue templates).

**Comment by DanielRuf** [comment]
Yes, please open a new one so we can track this better.

**Comment by ncoden** [comment]
Ok so #11469 removed the `is-active` class when menus where destroyed. But the bug in this issue and #11578 is for when the a submenu is closed. I'm reopening the issue.

**Comment by ncoden** [comment]
See https://github.com/zurb/foundation-sites/pull/11579
