### ISSUE TITLE
File '<path truncated>/dist/js/foundation.d.ts' is not a module

### ISSUE THREAD

**Issue by glen-84** [zurb/foundation-sites#11653]
## What should happen?

This error should not occur.

## What happens instead?

This error occurs when using TypeScript:

```ts
import Foundation from "foundation-sites";
```

## Possible Solution

Maybe this? https://github.com/zurb/foundation-sites/issues/11270#issuecomment-389546364

## Test Case and/or Steps to Reproduce (for bugs)

How to reproduce:
1. Use TypeScript 3.2.2
2. Install Foundation Sites using npm
3. Import Foundation as shown above

## Context

I'm trying to upgrade from Foundation Sites 6.4.3 to 6.5.1, which seems to be a breaking change.

`import "foundation-sites";` no longer works.

## Your Environment

- Foundation version(s) used: 6.5.1
- Browser(s) name and version(s): n/a
- Device, Operating System and version: Windows 10
- Link to your project: n/a
- TypeScript: 3.2.2
- Webpack: 4.28.4

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by glen-84** [comment]
I'm also affected by https://github.com/zurb/foundation-sites/issues/11586 – will v6.5.2 be released (very) soon?

**Comment by glen-84** [comment]
```ts
import "foundation-sites";
```

Works again in v6.5.2.

**Comment by DanielRuf** [comment]
Sounds good. Is your issue resolved now?

**Comment by glen-84** [comment]
If:

```ts
import Foundation from "foundation-sites";
```

... is valid syntax, then no, it's not solved. I just don't use this method at the moment.

**Comment by DanielRuf** [comment]
It is a valid import as it contains all needed modules. See https://github.com/zurb/foundation-sites/blob/develop/js/foundation.js#L35 and https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L84

**Comment by DanielRuf** [comment]
> ```ts
> import "foundation-sites";
> ```
> 
> Works again in v6.5.2.

This is the default export, see https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L118

**Comment by DanielRuf** [comment]
It is a valid import. See https://github.com/zurb/foundation-sites/blob/develop/js/foundation.js#L35 and https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L84

> ```ts
> import "foundation-sites";
> ```
> 
> Works again in v6.5.2.

This is the default export, see https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L118 and https://github.com/zurb/foundation-sites/blob/develop/js/foundation.js#L36

**Comment by DanielRuf** [comment]
I guess you mean `import {Foundation} from "foundation-sites";`

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by DanielRuf** [comment]
I guess you mean `import {Foundation} from "foundation-sites";`

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import and https://github.com/zurb/foundation-sites/blob/develop/js/foundation.js#L35 and also https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L84

**Comment by DanielRuf** [comment]
I guess you mean `import {Foundation} from "foundation-sites";`

What you do is using the default export and giving it the name `Foundation`.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import and https://github.com/zurb/foundation-sites/blob/develop/js/foundation.js#L35 and also https://github.com/zurb/foundation-sites/blob/develop/js/entries/foundation.js#L84

**Comment by DanielRuf** [comment]
Do you know what we would have to change to get it properly working?

cc @samvloeberghs

**Comment by DanielRuf** [comment]
I'm closing this one here as duplicate of #11270. If you think this is not correct, please let us know.
