### ISSUE TITLE
Namespaced Reveal Events are Fired Twice

### ISSUE THREAD

**Issue by justrhysism** [zurb/foundation-sites#5482]
The new namespaced events are firing twice (at least for Reveal).

Demo can be seen here: http://codepen.io/justrhysism/details/mIzuq/

Comment out the new event, and bring in the old events which proves it's a new bug.

**Comment by jepser** [comment]
@connormckelvey +1 for this solution

**Comment by nesl247** [comment]
I don't get how this bug can be open for so long.

**Comment by pulcher** [comment]
+1 on needing a fix

**Comment by doxxon** [comment]
+1

**Comment by sojourning** [comment]
+1

**Comment by rossgzc** [comment]
+1

**Comment by cmdelatorre** [comment]
+1 on needing a fix

**Comment by nicholashead** [comment]
Thanks for the workaround. Is the long-term fix as simple as removing that first `.trigger('opened')` call?

**Comment by owlvark** [comment]
I think the fix has a typo:

`'fndnt.reveal'`  should be `'fndtn.reveal'`

**Comment by jeaniec** [comment]
Blerg, I fixed that typo, but I think something got messed up in a merge I was editing. Will re-commit.

**Comment by nicholashead** [comment]
@jeaniec  Sorry, this is not fixed (even with correcting the typo). The other events (opened, close, closed) are still firing more than once. And the fix as presented seems like a patch/hack without addressing the real problem. The real problem is calling .trigger() without the "namespace" and then calling it again with the namespace. Can we simply get rid of the non-namespaced call to .trigger() ? Or does it need to exist for legacy reasons?

**Comment by jeaniec** [comment]
Hey @nicholashead, sorry for the premature commit. When I tested the fix on my local machine, I wasn't getting double events but maybe I wasn't exactly duplicating the problem at hand. I'm going to put a pin in this and put it on our trello board (https://trello.com/b/QBPKlQqf/foundation-sites) to engineer a better namespacing system. Because it seems that a lot of our recurring issues have to do with conflicting namespace events and it appears there is a mishmosh of using the trigger method as well. 

In the mean time, if you want to submit a pull request with a temporary solution that better integrates @andrejpavlovic's fix, let me know.

**Comment by nicholashead** [comment]
@jeaniec it's okay, just there are namespace issues with all of the events (not just 'open'). Just wanted to make sure any fix, fixed all of them, not just one event type. Thanks!

**Comment by jeaniec** [comment]
@nicholashead Noted :)

**Comment by tl1181231** [comment]
@connormckelvey  @andrejpavlovic

both are good solution

**Comment by sandermarechal** [comment]
This is *still* an issue with Foundation 5.5.1. Can this issue at least be reopened?

**Comment by Sinetheta** [comment]
Confirmed still double firing. Bind to events without the reveal namespace as a workaround, eg: `closed.fndtn`.

**Comment by justrhysism** [comment]
+1 to reopen

**Comment by kylefox** [comment]
I noticed this as well in the latest version of [foundation-rails](https://github.com/zurb/foundation-rails) (5.5.1.2).

The workaround suggested by @Sinetheta worked for me.

**Comment by jeanieshark** [comment]
For those still experiencing double firings of the event, could you provide a code snippet with the double firings as well as the browser you're using? I'm having a hard time recreating this issue on the master branch with past examples.

**Comment by nicholashead** [comment]
@jeanieshark the original codepen still shows 'opened' being triggered twice, even after pointing at the latest version of Foundation (5.5.1)

**Comment by jeanieshark** [comment]
@nicholashead Ah, I think I see the problem. I don't think my fixes were committed as of the latest release, because I'm not finding any instances of .trigger() with non-namespaced events in my local copy (master). That might be why we're experiencing a discrepancy with this. I know that @rafibomb wanted to try to release next week, so we can see if that will solve the problem.

I put the same code that is found in the CodePen and ran it on my local machine (master) and I was only experiencing single event firings. Same goes for the code in #6482. If you have a current issue that you have on your local branch, do you mind trying to pull down master to see if you continue to experience the same issue?

**Comment by nicholashead** [comment]
@jeanieshark it appears to be working correctly when you pull from `master`.

**Comment by jcrawford** [comment]
I am using 5.5.2 and I just had to track down this issue while using Dropzone uploading component, it was being initialized twice and finally found that the event was firing twice.  Is this still a valid bug or should it be resolved in 5.5.2?

**Comment by zurbchris** [comment]
I don't know about 5.5.2, but I just tested in 5.5.3 and it is resolved there. If anyone is still having an issue with this, please let us know. Sorry about the staleness.
