### ISSUE TITLE
[Orbit Slider] $curSlide[0] is undefined

### ISSUE THREAD

**Issue by bnbc** [zurb/foundation-sites#7079]
Error: $curSlide[0] is undefined : on this page : http://presticar-automobiles.com/

**Comment by gakimball** [comment]
Can you post the code used to create the Orbit slider here for reference?

**Comment by zurbchris** [comment]
Sorry, I know the issue. You didn't add an `is-active` class to any of the slides. I've fixed it in the dev branch 8efcde that patch will be out today.

**Comment by bnbc** [comment]
Thanks for your great job !

**Comment by Kevin8428** [comment]
I have this code and am still getting the same error, my images load but it's as though jquery isn't running and no animation or slide is occurring, any idea why this might be happening?

**Comment by AIMMOTH** [comment]
I get the same error when I use Angular with ng-repeat for all images. When I change the array of images this error show up and the orbit can't change image.
