### ISSUE TITLE
Uncenter(ed) not working in Foundation 6

### ISSUE THREAD

**Issue by Nostalginen** [zurb/foundation-sites#7183]
Firstly noticed that uncentered is renamed to uncenter (in docs it still says uncentered though).
So i was trying to build "small-10 small-centered large-4 large-uncenter" column that would be centered in small and medium but floated in large, but it stays centered all the way. Applied a quick fix with !important to uncenter margins. Works for me right now :), but might not the best solution.

/// Reset a position definition.
@mixin grid-column-unposition() {
  position: static;
  margin-left: 0 !important;
  margin-right: 0 !important;
}

**Comment by rafibomb** [comment]
I made a codepen demo to show it - http://codepen.io/rafibomb/pen/bVPeQW

Reported here: http://foundation.zurb.com/forum/posts/36327-centered-columns-not-working-for-me

**Comment by donaldG** [comment]
Err, supposing this didn't role out w/ v 6.0.5? Just curious :smiley_cat:

**Comment by gakimball** [comment]
Nope, our apologies! We'll make sure it's done before 6.1, which will be out in a week or so.

**Comment by donaldG** [comment]
Beautiful, thanks!! Loving this new F6, btw!

**Comment by Pautomagi** [comment]
I tried to apply the fix that @Nostalginen posted, but without luck. It falls back to margin: auto; anyways.

Does anyone have another solution ?

Great work with F6 so far, looking forward to v6.1!

**Comment by gakimball** [comment]
Fixed! We also decided to change that class back to `-uncentered`, to keep it consistent with Foundation 5.

**Comment by donaldG** [comment]
You rock!! Thanks for all your hard work (and everyone's!). F6 is totally
killer. Demoed a new workflow for our team using Gulp & Sass yesterday and
I'm super excited to be working with the new version of the framework!

**Comment by marcdittmann** [comment]
Hi, 

i think there is still an issue with large-uncentered in 6.1.1. 

**small-centered** adds:
```css
float:none;
```

but **large-uncentered** will not add 
```css
float:left;
```
 again so the single columns will not align in a row.

Heres an simple example
http://codepen.io/anon/pen/BjZGMV

another is that theres an problem with *-centered and 'end'

**Comment by gakimball** [comment]
@marcdittmann `float: left` was added here: 34cb85622e459cae13aea90252a54fe8a18dc81d

**Comment by eu-slack** [comment]
There's another issue:

**medium-centered** adds on last **column**:
```
.medium-centered, 
.medium-centered:last-child:not(:first-child) {
  float: none;
  clear: both;
}

```
but for **large-centered** adds only:
```
.large-uncentered, 
.large-push-0, .large-pull-0 {
  position: static;
  float: left;
  margin-right: 0;
  margin-left: 0;
}
```
so last column will **not** align correctly.

I think the last _uncentered_ column needs also:
```
@media print, screen and (min-width: 40m) {

  .column.medium-uncentered:last-child,
  .columns.medium-uncentered:last-child {
    clear: none;
    float: right;
  }
}

@media print, screen and (min-width: 64em) {

  .column.large-uncentered:last-child,
  .columns.large-uncentered:last-child {
    clear: none;
    float: right;
  }
}
```

Here's a simple example with the suggested solution: https://codepen.io/eu-slack/pen/gWBjrB
