### ISSUE TITLE
Foundation Tabs Uncaught TypeError

### ISSUE THREAD

**Issue by bigandy** [zurb/foundation-sites#7327]
Getting a console message when I try and use foundation tabs. 

`script.min.js:1 Uncaught TypeError: Cannot read property '_init' of undefined`

unless I also include `foundation.util.mediaQuery.js` which [the docs](http://foundation.zurb.com/sites/docs/tabs.html#javascript-reference) do not reference.

**Comment by zurbchris** [comment]
So, all js-based plugins are dependent on the mediaQuery library, or at least part of it. We are debating putting it in .core.
Thanks for letting us know.

**Comment by komarnicki** [comment]
Hi @bigandy, your suggestion about including `foundation.util.mediaQuery.js` solved my problem with Tooltips. Everything was working fine when I was including `foundation.js` from `dist`, but because I don't want all plugins, I started including just those plugins that I really need.

Unfortunately for `tooltip` the solution written in [the official documentation!](http://foundation.zurb.com/sites/docs/tooltip.html) didn't work. After I added `foundation.util.mediaQuery.js` it started working.

I also saw another mismatching. In docs of version 5, Zurb says that Orbit will be deprecated while it still exists in 6.0.5 but none of the examples form official page work on localhost. After first slide, it stops.

Zurb, I'm new to foundation and so far I like it very much but please, improve all docs. This is an essential starting point for developers. Without proper instructions, beginners with Foundation are half-blind trying to make things work.

**Comment by zurbchris** [comment]
I agree the docs need to be improved quite a bit for clarity. We're going to put the media query util in .core in 6.1, so that will at least solve one problem. Thanks.
Otherwise, it seems this problem was resolved, closing it down.

**Comment by purplespider** [comment]
Forgive me if I'm wrong, but it doesn't look like mediaQuery.js has been incorporated in core.js yet? I still get this issue with 6.1 (and 6.2).

**Comment by adamplabarge** [comment]
Seems like it is still an issue to me.  Using foundation-sites and 6.2.1.

zurbchris - at least update the documentation on this page (http://foundation.zurb.com/sites/docs/javascript.html) to say what is REQUIRED

Between getting gulp babel working and this, serious a frustrating experience integrating foundation-sites into a project.
