### ISSUE TITLE
ul,ol margin-left being overridden by ul{margin-left} in foundation.min.css

### ISSUE THREAD

**Issue by Ross-AW** [zurb/foundation-sites#7656]
I think there is an issue in the minified CSS; I have downloaded the latest from github but Codepen only has 6.0.5 and the issue is present. The ul,ol {margin-left} is being overwritten by a later declaration of ul,ol{margin:0}

Minified 6.0.5 (https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.5/css/foundation.min.css)
http://codepen.io/anon/pen/vLKRMN

Codepen using non-minified: (https://cdnjs.cloudflare.com/ajax/libs/foundation/6.0.5/css/foundation.css)
http://codepen.io/anon/pen/jWrzRY

    //line 1257
     ul { 
	    list-style-type: disc;
	    margin-left: 1.25rem;
     }

	//line 1247
	ul, ol, dl {
	    line-height: 1.6;
	    margin-bottom: 1rem;
	    list-style-position: outside;
	}
	//line 1134
	div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, pre, form, p, blockquote, th, td {
	    margin: 0;
	    padding: 0;
	}

**Comment by gakimball** [comment]
I updated the two CodePens to 6.1.0 and the visuals were identical. Seems to have been fixed!

**Comment by pzi** [comment]
Either the problem is back or there is a new discrepancy:
Using dist CSS: http://codepen.io/anon/pen/PZOrVz
Using minified CSS: http://codepen.io/anon/pen/bEYPzq

`margin-left` gets overwritten in min.

**Comment by andycochran** [comment]
Here's v6.2.3 min: http://codepen.io/andycochran/pen/bZAZkR
Seems to work. Gonna close this. Please reopen if the issue pops its head back up.
