### ISSUE TITLE
Allow data-toggle to trigger multiple elements

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-sites#7806]
Specifically when prototyping with Toggler, being able to fire `toggle` events on multiple elements would be useful.

```html
<a data-toggle="elementOne elementTwo"></a>
```

This should apply to `data-open` and `data-close` as well.

**Comment by zurbchris** [comment]
Shouldn't be too hard.

**Comment by gakimball** [comment]
True that! It's not a priority for 6.2 though, most likely.

**Comment by twd3** [comment]
This would be really cool. You guys rule!

**Comment by Lynda333** [comment]
+1 - This would be real useful!

**Comment by andrewbiddinger** [comment]
:+1: A must have...

**Comment by zurbchris** [comment]
done.

**Comment by gakimball** [comment]
95285e5c2f4eac5ac68ab0be43e7364c469e8006

**Comment by BryanBarrera** [comment]
Is this supported yet? I'm using 6.2.1 but still can't use data-toggle to toggle more than 1 element.
