### ISSUE TITLE
6.2.0-rc.1 package.js: Blocking Issue:  parse error

### ISSUE THREAD

**Issue by mhair** [zurb/foundation-sites#8203]
I have manually merged in the changes from this branch since this appeared to be the only way to do update. Let me know if I'm wrong about that.

Upon "foundation watch", I get an unexpected token 'n' at 2:3, refering to the  n in name, the first pair in the first line of the "package.describe". 

I've also noticed that when I view the code in github raw, I get "Error: Parse error on line 1: { name:....
Expecting 'STRING', '}'

I've tried many different things regarding JSON syntax but have not been able to resolve this.

Has anyone else experienced this, and can anyone recommend the solution? It is blocking me from testing this release.

**Comment by gakimball** [comment]
Are you using Foundation with Meteor?

**Comment by mhair** [comment]
No, but I came to the conclusion that I'm trying to use package.js and package.json that were created for foundation proper, not for the zurb template which is what I'm using and upgraded this project for based on https://github.com/zurb/foundation-sites/releases/tag/v6.2.0-rc.1, The only problem is that the instructions were a bit confusing regarding the zurb template, at least from where I stand. So I'm planning to revert to my code prior to this merge and forget about trying to help test  this release. 

There are just so many moving parts in Foundation these days, so many dependencies to debug (Windows node-gyp anyone?), and the documentation (including link just given) is just not explicit enough to suss it all out. I end  up wasting tons of time trying to debug the use of the framework rather than getting real work done. I'm not going to add anything more since the post "So Long and Farewell" which summed up the pain I've been having. I'm not giving up yet(!), and am really hopeful for 6.2, but I can't even test it based on not having clear and explicit information to update the install of zurb template that I've been working with. I'll just have to wait for it to be released and then do a more complete evaluation. Even then I wouldn't give up on Foundation, but would revert to the latest 5.x. However, that would be a big setback and disappointment for me and those I've convinced 6.0 was worth basing this project on.

**Comment by gakimball** [comment]
I was asking about Meteor since you referenced `package.js`, which is only read by Meteor. I wasn't sure how running `foundation watch` (which runs `gulp`) could create an error with `package.js`—in a non-Meteor build process, that file isn't being referenced at all.

I hear you on the frustrations around the build process—I spent around 15–30 minutes a day helping my coworkers debug Node errors. But these aren't problems exclusive to Foundation, they're unfortunately just inherent to the current state of web tooling.

To be sure, we've been pretty heavily pushing our userbase *towards* more modern tooling, which results in a lot of thrash. This is as opposed to more basic ways like having a straight ZIP file with precompiled CSS and JavaScript. It's still possible to use Foundation without all of the bells and whistles, but our documentation tends to skew more towards advanced developers. We've been having some internal discussions on how we position Foundation, and if we're neglecting the basics more than we think.

Could you elaborate on what parts of the 6.2 migration you found unclear or confusing? I'd like to refine it before 6.2 comes out next week, so your feedback would be really helpful.

**Comment by mhair** [comment]
Geoff,

I apologize. I didn't mean to pile on, I'm just frustrated and trying to move on with my work. I will hold off on reverting to 6.1.2 for a bit to see if you can help me figure out what is going on.

**Comment by mhair** [comment]
As to feedback, I did read "how to upgrade" before upgrading my existing project. I jumped to that part of the document to carefully read those parts and execute what they were saying, then returned to the top. Normally, from my understanding, "bower update" would be the way to do the update, but instead you seemed to be indicating that npm install foundation-sites@beta would do the update. So I tried it, but it did not update my code. I decided to just merge in the changes by comparing the Foundation-sites equivalent folder in 6.2.0 RC1 and my zurb template equivalent folder. I noted that the package.json and package.js were not part of the zurb template foundation-sites structure, so I didn't know what to do with them, leaving them in place in the foundation-sites origin. I tried foundation watch  after the merge, and I don't recall what errors caused me to think I needed to move those two files up to the zurb template root (renaming the old package.json), but I did, and that is when I got the parse errors indicated.

So I've since moved the 2 files back into the foundation-sites folder and reverted to the original package.json associated with zurb template. This seems to have gotten me further down the road, but still new problems. Upon executing foundation watch, I now get errors indicating that rem-calc is being passed "small 20px" which is not a number, but I can assure you that I'm not passing that anywhere in my code, only numbers/no alphas…. Resulting in the app.css is not being compiled. Please enlighten me if you know what would be causing this. My searches have turned up nothing.

I'm also getting notice further down in the terminal output: [BABEL] Note: The code generator has deoptimized the styling of ……..app.js" as it exceeds the max of "100KB". The end result is that appears to be watching and serving files from "dist" but my zurb template based page is no longer styled or js'd. Go figure, this is my result of "updating" to 6.2rc. As I said. These are the types of frustrations that have haunted me throughout my "modern tooling" with Foundation 6.x.

Regarding your general comments about the state of modern tooling, I'm not the only one questioning whether the current node package dependency-crazy tooling (especially on Windows it would seem) is a step forward due to the level of chaos inherent in it. It does make me consider strongly going back to a standard compiler such as pre-pros even though I like others, want to stay on the leading edge….and yes, I understand that pre-pros has nowhere near the utility (like uncss, etc.), assuming that the utility is actually functional instead of just a perpetual headache.

Regarding your comment about your "documentation tends to skew more towards advanced developers," I think it always pays to remember that because you're paid to work on the tooling  and the framework all day long, those who are trying to use it are not, which can cause you to lose site of the forest. Developers like myself are resorting to a framework as a means to an end, and we are de facto generalists because we have such broad roles and responsibilities that there is no way that we can be as deep into the tooling and the technologies behind it as you are. So you do indeed tend to make too many assumptions in conveying many of the basics because you are "soaking in it", whereas people like myself are a single designer/developer covering an entire 10 person team's responsibilities, on 5 different sites. It is not as if we wouldn't prefer to stop the world and go deeper than our jobs allow us to, but sheer constraint of unrealistic job scope prevents that. So I would caution you not to be condescending when thinking about your users.

With all of the above said, can you help me to remain on 6.2rc and get past these compiling errors, or should I revert so that I can get back to work? Please respond ASAP.

**Comment by gakimball** [comment]
To address each of your issues:

1. Our Sass templates manage the Foundation dependency through Bower, not npm. So installing a new version of Foundation through npm won't do anything.
2. As for the Sass error, I think it's cropping up anywhere you use `rem-calc()` with `$grid-column-gutter` if I had to guess. Could you post a full stack trace of the error?
3. For the Babel error, try placing `.pipe(babel())` *above* `.pipe(concat())` in your Gulpfile. The upgrade guide will be updated to reflect this.

Regarding the documentation, you're absolutely right. We've been reviewing our messaging and positioning for the framework, and one thing coming out of that is that we're losing sight of the basics. You can even see this on the [landing page](http://foundation.zurb.com/sites.html) for Sites—it talks a lot about new features, or how our framework is different from others, or advanced stuff, but not enough time talking about *what a framework actually is*. So know that we're aware of the knowledge gap that exists in our messaging and our documentation, and we aim to address it.

Lastly, I'll say thank you so much for trying out the release candidate. This is something we've never done before—we tend to just release minor versions with no build-up. We're trying to put new stuff out in the open sooner so we can identify issues ahead of the time. It means a lot that you'd take the time to break down the problems you've been having, so thank you for that.

**Comment by mhair** [comment]
Agree that it is due to $grid-column-gutter, had concluded that prior to your response since the errors show 20px and 30px passed to rem-calc, and these are the values that I see were copied from $grid-column-responsive-gutter to $grid-column-gutter per your instruction. Their previous (and untouched) value was as such:
`
$grid-column-gutter: (
        small: 20px,
        medium: 30px,
);
`
Changing the value to: 
$grid-column-gutter: 20px;
did indeed resolve the rem-calc error, which begs the question of why these instructions are being given to your users if they've not been tested. 

I moved .pipe(babel()) above .pipe(concat()) which had the same result of complaining about the 100KB max, but at least with the rem-calc error gone now I'm able to move forward since the page is now rendering. 

So this does underscore the frustrations that users such as [Russel Porosky](http://foundation.zurb.com/forum/posts/38374-so-long-and-farewell) have been venting. All of this has taken 2 full days of my time this week that I was not getting anything productive done towards MY goals and work. 

I appreciate your help today Geoff, and I appreciate your comments recognizing my effort. However, I'll have to say that I feel like I'm doing someone else's job here, crossing i's and dotting t's rather than confirming something that has already been tested. If that was your intent of asking people to test a release candidate, then I think that is the wrong approach. If you're going to ask, I believe the code should be tested first. For those that wish to be developers on your project, that's one thing, but for those that are simply trying to get work done using your project, that is quite another. I think you have to differentiate.

Since at least I'm rendering now, I'll just close this and wait for the release to get rid of the Babel error.

Thanks,
Mark
==================== Trace Below =======================
C:\Users\mhair.ICS\Documents\Websites\foundation6.dev>foundation watch

> foundation-zurb-template@1.0.0 start C:\Users\mhair.ICS\Documents\Websites\foundation6.dev
> gulp

[16:09:46] Using gulpfile ~\Documents\Websites\foundation6.dev\gulpfile.js
[16:09:46] Starting 'build'...
[16:09:46] Starting 'clean'...
[16:09:46] Finished 'clean' after 40 ms
[16:09:46] Starting 'pages'...
[16:09:46] Starting 'sass'...
[16:09:47] Starting 'javascript'...
[16:09:48] Starting 'images'...
[16:09:48] Starting 'copy'...
WARNING: small 20px was passed to rem-calc(), which is not a number.
        on line 75 of bower_components/foundation-sites/scss/util/_unit.scss
        from line 48 of bower_components/foundation-sites/scss/util/_unit.scss
        from line 84 of bower_components/foundation-sites/scss/grid/_row.scss
        from line 44 of bower_components/foundation-sites/scss/grid/_classes.scss
        from line 20 of stdin

WARNING: medium 30px was passed to rem-calc(), which is not a number.
        on line 75 of bower_components/foundation-sites/scss/util/_unit.scss
        from line 48 of bower_components/foundation-sites/scss/util/_unit.scss
        from line 84 of bower_components/foundation-sites/scss/grid/_row.scss
        from line 44 of bower_components/foundation-sites/scss/grid/_classes.scss
        from line 20 of stdin

[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/mhair.ICS/Documents/Websites/foundation6.dev/bower_components/jquery/dist/jq
uery.js" as it exceeds the max of "100KB".
Error in plugin 'sass'
Message:
    bower_components\foundation-sites\scss\util\_unit.scss
Error: invalid operands for multiplication
        on line 48 of bower_components/foundation-sites/scss/util/_unit.scss
>>     $rem-values: append($rem-values, -zf-to-rem(nth($values, $i), $base));
   -----------------^

[16:09:50] Finished 'sass' after 3.64 s
[16:09:50] Finished 'pages' after 4.15 s
[16:09:51] Finished 'copy' after 2.48 s
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/mhair.ICS/Documents/Websites/foundation6.dev/src/assets/js/foundation.js" as
 it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/mhair.ICS/Documents/Websites/foundation6.dev/src/assets/js/foundation.min.js
" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/mhair.ICS/Documents/Websites/foundation6.dev/src/assets/js/holderjs/holder.j
s" as it exceeds the max of "100KB".
[16:09:57] Finished 'javascript' after 10 s
[16:09:57] Finished 'images' after 9.46 s
[16:09:57] Starting 'styleguide'...
[16:09:57] Finished 'styleguide' after 26 ms
[16:09:57] Finished 'build' after 11 s
[16:09:57] Starting 'server'...
[16:09:57] Finished 'server' after 46 ms
[16:09:57] Starting 'default'...
[16:09:57] Finished 'default' after 132 ms
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:8000
    External: http://164.165.55.149:8000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://164.165.55.149:3001
 ---------------------------------------
[BS] Serving files from: dist

**Comment by mhair** [comment]
Now that I think about it, I'll reopen it, otherwise the Babel issue will never be addressed.

**Comment by gakimball** [comment]
Updated: zurb/foundation-zurb-template@b7585fd0ba9248f85adbae114bc0d96f5a79bf2f

6.2 is coming out at the end of the week, so it would have been addressed. :)

And thanks again for your feedback and patience.

**Comment by mhair** [comment]
So considering that the change committed above doesn't solve my problem, I assume that this is simply a warning that can either be resolved elsewhere with gulpfile options changes, or will be documented in the release as "just a warning?"

Thanks for all your hard work on this. I know you guys are busting it to make things go smoother.
