### ISSUE TITLE
Callout makes reveal close (bug) (again)

### ISSUE THREAD

**Issue by Silvester20** [zurb/foundation-sites#8428]
And this bug ( https://github.com/zurb/foundation-sites/issues/7833 ) is there again in Foundation 6.2.0.

CodePen: http://codepen.io/anon/pen/xVgmqx

**Comment by Owlbertz** [comment]
I did something to prevent this in this commit https://github.com/Owlbertz/foundation/commit/4e01cecca10ba4f4dee3e39b504c6567ef1258c1. But as mentioned the solution may not be ideal. I don't know why the `stopPropagation()` doesn't work as intended...
Maybe someone has some feedback or solution to this.

**Comment by Silvester20** [comment]
Will be very nice if this is the next release, thank you so much!

**Comment by kball** [comment]
Fixed by #8471, will be in 6.2.2

**Comment by Silvester20** [comment]
Amazing, a big thanks to @Owlbertz and ofourse @kball !

**Comment by rui-castro** [comment]
@Owlbertz @kball  This bug still exists in foundation 6.4.3.

Using something like the example bellow; clicking callout close button closes the reveal.

```html
<div class="reveal reveal-animated">

        <div class="callout warning" data-closable>
            <button class="close-button" aria-label="Close warning" type="button" data-close>
                <span aria-hidden="true">&times;</span>
            </button>
            Callout text
        </div>

    <a aria-label="Close" data-close>&#215;</a>
</div>
```
