### ISSUE TITLE
npm start or foundation watch or gulp command doesn't do what advertised

### ISSUE THREAD

**Issue by seanmavley** [zurb/foundation-sites#8897]
**How can we reproduce this bug?**
 I run
`foundation new 
? What are you building today? A website (Foundation for Sites)
? What's the project called? (no spaces) side
? Which template would you like to use? Basic Template: includes a Sass compiler

[download/install output here]

You're all set!

 ✓ New project folder created.
 ✓ Node modules installed.
 ✓ Bower components installed.

Now run foundation watch while inside the side folder.

cd side/
foundation watch

> foundation-sites-template@1.0.0 start /home/khophi/Developments/WebSites/side
> gulp

[13:13:51] Using gulpfile ~/Developments/WebSites/side/gulpfile.js
[13:13:51] Starting 'sass'...
[13:13:52] Finished 'sass' after 822 ms
[13:13:52] Starting 'default'...
[13:13:52] Finished 'default' after 8.32 ms

**What did you expect to happen?**
According to the docs:

> Finally, run npm start to run Gulp. Your finished site will be created in a folder called dist, viewable at this URL: http://localhost:8000

I expected to see http://localhost:8000 open in my browser, or at least, if that didn't happen auto, going to that address myself should open the project. None worked.

**What happened instead?**
Nothing happens after the `Finished 'default' after 8.32 ms`. No page in browser opens nor localhost:8000 isn't up.

Please somebody tell me there's something I am not reading. I am following the /installation.html of the v6.2.2

**Comment by carpusmedia** [comment]
Hello Sean,

Are you developing locally on your PC/Mac? I think you need to open the site (http://localhost:8000) yourself. 

If the page not loading for you, try http://localhost without the port. The port only works if you have BrowserWatch installed and configured in your gulpfile.js.

Have a great day Sean

**Comment by sharathsreenivasan93** [comment]
Hi Sean,

Please let me know if you were able to solve the problem.  I am facing the same issue.

Sharath.

**Comment by seanmavley** [comment]
@sharathsreenivasan93 I couldn't get it to work. Moved on with my life!

**Comment by sharathsreenivasan93** [comment]
I used a different browser and it worked just fine. Switched from Chrome to Safari.

**Comment by kball** [comment]
This looks like it has been resolved above, but please reopen if you're still having trouble.

**Comment by jel111** [comment]
This is happening to me. No error in terminal and everything shows up fine in the files when I open them in the editor. I tried running npm start and foundation watch and the same thing happens. I tried three browsers and all different combinations of Localhost. Nothing works. Where above was this resolved?

**Comment by sharathsreenivasan93** [comment]
For me it worked when I switched from Chrome to Safari. I'd recommend you move on if switching browsers doesn't solve your problem.

**Comment by jel111** [comment]
What just not use foundation cli?

**Comment by Baggio89** [comment]
You have git cloned **foundation-sites-template** 
`git clone https://github.com/zurb/foundation-sites-template projectname`

This template only compiles sass. The template you want is with browsersync, javascript, panini etc... To solve your problem:

You should git clone: **foundation-zurb-template**
`git clone https://github.com/zurb/foundation-zurb-template projectname`
