### ISSUE TITLE
Magellan update event fires too often.

### ISSUE THREAD

**Issue by Owlbertz** [zurb/foundation-sites#9068]
I feel like the Magellan `update.zf.magellan` fires too often.
The docs state that it "Fires when magellan is finished updating to the new active element.", but as seen in the image it fires more often making it not usable to reliable hook into **after** the update process.

![image](https://cloud.githubusercontent.com/assets/4280373/17270383/a7558452-5661-11e6-9c38-5e0f6c079e07.png)

**Comment by kball** [comment]
Definitely the case. It appears to fire continuously on scrolling updates, and I'm seeing it anywhere from 2 to 6 times on clicking an update in the `active-item.html` visual test.

It looks like there's a lot of functionality running each time (including manipulating classes) that really shouldn't be... I think the fix is to either check the class to find current active target, or probably better keep a JS reference to current active index, and bail early around https://github.com/zurb/foundation-sites/blob/develop/js/foundation.magellan.js#L156 if index hasn't changed.

**Comment by Owlbertz** [comment]
Bump @kball

**Comment by kball** [comment]
@Owlbertz thanks for prodding - been slammed with some other stuff, do you have time to take a look?

**Comment by coreysyms** [comment]
Hey fellas, just ran into this issue and solved it for me by doing this. Not sure if it is the best solution for the rest of the world, but wanted to share to see if it perked anyone else's mind. I basically just use the logic that is in place to my advantage, which in _updateActive states. Take all hrefs and removed the active class, then apply active to the one that is currently calculated as active. I slipped this "if" in between the remove and update active class to grab the current and see if the href is the same as the one being applied the active class.

```
this.$active.removeClass(this.options.activeClass);

if ($(this.$active[0]).attr("href") !== $(this.$links.filter('[href="#' + this.$targets.eq(curIdx).data('magellan-target') + '"]')[0]).attr("href")) {
  this.$element.trigger('update.zf.magellan', [this.$active]);
}

this.$active = this.$links.filter('[href="#' + this.$targets.eq(curIdx).data('magellan-target') + '"]').addClass(this.options.activeClass);
```

The trigger only fires when the href is actually different from the previous one. Running 6.3.0

**Comment by brettsmason** [comment]
@Owlbertz @coreysyms This looks like something that should be fixed but my JS knowledge is limited.
Any suggestion on what to do with this?

**Comment by coreysyms** [comment]
this is not fixed. just tested. I can push a PR something to fix it.

**Comment by coreysyms** [comment]
If someone would like to double check this, please do.
