### ISSUE TITLE
[Flex Grid] Topbar alignmnet issue with Flex Grid

### ISSUE THREAD

**Issue by zarinbal** [zurb/foundation-sites#9197]
The top bar does not work properly in flex system.

**How can we reproduce this bug?**
 I used the topbar example in flex system.

**What did you expect to happen?**
The top-bar-right should align to right of page.
http://codepen.io/azm_64/pen/RGoQLr

**What happened instead?**
The top-bar-right dos not stick to the left of page and it  is in middle 
http://codepen.io/azm_64/pen/ALpVrW

**Comment by kball** [comment]
Fixed in https://github.com/zurb/foundation-sites/pull/9177, will be in 6.2.4 which should be released in the next few weeks.

**Comment by adamthedeveloper** [comment]
I'm using 6.3+ and this still isn't working for me. Have you confirmed that this works currently for top bars with title, left, and right? Can you look at this example?

`<div class="top-bar">
    <div class="top-bar-title">
        <button class="menu-icon dark hide-for-medium" type="button" data-open="leftOffCanvas"></button>
        <strong>BRILLIANT</strong>
    </div>
    <div class="show-for-medium">
        <div class="top-bar-left">
            <ul class="dropdown menu" data-dropdown-menu>
                <li>
                    <a href="#">Inspiration</a>
                    <ul class="menu vertical">
                        <li><a href="#">Inspiration 1</a></li>
                        <li><a href="#">Inspiration 2</a></li>
                        <li><a href="#">Inspiration 3</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">Services</a>
                    <ul class="menu vertical">
                        <li><a href="#">Services 1</a></li>
                        <li><a href="#">Services 2</a></li>
                        <li><a href="#">Services 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>


        <div class="top-bar-right">
            <ul class="dropdown menu" data-dropdown-menu>
                <li>
                    <a href="#">Start a project</a>
                </li>
                <li>
                    <a href="#">Account</a>
                    <ul class="menu vertical">
                        <li><a href="#">Account 1</a></li>
                        <li><a href="#">Account 2</a></li>
                        <li><a href="#">Account 3</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#"><i class="fa fa-shopping-cart"></i>Cart</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="top-bar-title float-right top-bar-title-right hide-for-medium">
        <strong>&nbsp;</strong>
        <button class="menu-icon dark hide-for-medium" type="button" data-open="rightOffCanvas"></button>
    </div>
</div>`
