### ISSUE TITLE
Off-Canvas v6.3 does not scroll on mobile.

### ISSUE THREAD

**Issue by jinch** [zurb/foundation-sites#9696]
If your off-canvas menu is longer than the visible area on mobile, you can't scroll to see the rest of the content. Scrolling only seams to work on desktop.

[EXAMPLE HERE](http://inchdesigns.com/projects/OFFCANVAS/) // tested in Android Chrome as well as iOS Safari. In both cases you can't scroll to see the rest of the menu when the Off-Canvas menu is open.

**Comment by brettsmason** [comment]
@jinch Thanks for reporting this issue.

I have looked into it myself and can confirm it appears to be an issue with `data-content-scroll`.
See [this CodePen](http://codepen.io/brettsmason/pen/PWKZEe) to demonstrate the bug.

I'll look into this and see if I can find a way to fix it.

**Comment by kball** [comment]
Submitted PR to address this: #9707.  @brettsmason would appreciate your testing

**Comment by kball** [comment]
This was fixed in #9707, should be working in 6.3.1

**Comment by m-lamarre** [comment]
I have a question about this issue @kball 🤓 
I am currently using the `foundation-rails (6.4.1.3)` gem on my Rails project, and I am still experiencing this issue on Android mobile devices still.

If I set `data-content-scroll=''` to false, I am not able to scroll in `offCanvasMenu` on my android device at all. When set to `true` I am able to scroll in the OffCanvasMenu but then the background scrolling is visible from the hamburger menu.

I see that your fix was for iOS `Enable scrolling within offcanvas panel on iOS` 
Has this not been fixed for Android? 🤔

**Comment by m-lamarre** [comment]
Alright, well I managed to find this link:
[Disable background scrolling when mobile menu is active](https://forum.webflow.com/t/disable-background-scrolling-when-mobile-menu-is-active-opened/38305)

and I just modified the code slightly to work for Foundation 6.
`data-content-scroll='true'` on the `#offCanvasMenu`

```
<script>
  $('.off-canvas').on('opened.zf.offcanvas', function(e) {
    e.preventDefault();
    $('body').css('overflow', 'hidden');
  });

  $('.off-canvas').on('closed.zf.offcanvas', function(e) {
    e.preventDefault();
    $('body').css('overflow', 'auto');
  });
</script>
```

**Comment by jinch** [comment]
@m-lamarre - thanks for that solution. I just found the same issue on Android and this helped resolve it. For me - i was able to scroll (using v6.3.1) ~ even with `data-content-scroll=''false"` however I found that if you scrolled to the very bottom of the off-canvas menu the scrolling would stop and I was not able to scroll after that. This may have been addressed in another patch but it sounds like there are still some issues with this.

**Comment by bsurai** [comment]
> I found that if I set `data-transition="overlap"` the scrolling would stop when you reached the bottom of the off-canvas menu and you would not be able to scroll back up. This may have been addressed in another patch since that release but it sounds like there are still some bugs with this.

@jinch @kball Have you got a solution for this issue? I see that issue with Chrome on Android.

**Comment by DanielRuf** [comment]
Please try Foundation 6.6.3. 6.3 is very old and we have resolved many issues since then.
